name: 'Hello World'
description: 'Greet someone and record the time'
inputs: # input parameters are stored as environment variables on the Runner/CI server.
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12' # javascript action.
  main: 'index.js'